// frontend/src/components/Layout.vue
<script setup>
import { computed } from 'vue';
import { useAuthStore } from '../stores/auth';
import Sidebar from './Sidebar/Sidebar.vue';

const auth = useAuthStore();
const showSidebar = computed(() => auth.isAuthenticated);
</script>

<template>
  <div :class="['layout', { 'with-sidebar': showSidebar }]">
    <Sidebar v-if="showSidebar" />
    <main class="main-content">
      <RouterView />
    </main>
  </div>
</template>

// frontend/src/components/Layout.jsx
import React from 'react';
import { Outlet } from 'react-router-dom';
import Sidebar from './Sidebar/Sidebar';
import { useAuth } from '../context/AuthContext';

export default function Layout() {
  const { user } = useAuth();
  const showSidebar = !!user;

  return (
    <div className={`layout ${showSidebar ? 'with-sidebar' : ''}`}>
      {showSidebar && <Sidebar />}
      <main className="main-content">
        <Outlet />
      </main>
    </div>
  );
}
