// frontend/src/components/Sidebar/Sidebar.jsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { useModules } from '../../hooks/useModules';

export default function Sidebar() {
  const { user, logout } = useAuth();
  const modules = useModules();

  return (
    <nav className="sidebar">
      <div className="sidebar-brand">Small CMR</div>
      <ul className="sidebar-nav">

        {modules.ore && (
          <>
            <li className="sidebar-section-label">Gestione Ore</li>
            <li><NavLink to="/ore">Inserimento Ore</NavLink></li>
            {user?.ruoli?.some(r => ['admin', 'gestore_commesse'].includes(r)) && (
              <li><NavLink to="/gestione-commesse">Gestione Commesse</NavLink></li>
            )}
          </>
        )}

        {modules.richieste && (
          <>
            <li className="sidebar-section-label">Gestione Richieste</li>
            <li><NavLink to="/" end>Prenotazioni</NavLink></li>
            {user?.ruoli?.some(r => ['admin', 'validatore'].includes(r)) && (
              <li><NavLink to="/approvazioni">Approvazioni</NavLink></li>
            )}
          </>
        )}

        {modules.password && (
          <>
            <li className="sidebar-section-label">Vault</li>
            <li><NavLink to="/vault">Password</NavLink></li>
          </>
        )}

        <li><NavLink to="/profilo">Il mio Profilo</NavLink></li>

        {user?.ruoli?.includes('admin') && (
          <>
            <li className="sidebar-section-label">Anagrafiche</li>
            <li><NavLink to="/utenti">Utenti</NavLink></li>
            <li><NavLink to="/ditte">Ditte</NavLink></li>
            <li><NavLink to="/teams">Team</NavLink></li>
          </>
        )}

      </ul>
      <div className="sidebar-footer">
        <span className="sidebar-user">{user?.nome} {user?.cognome}</span>
        <span className="sidebar-role">{user?.ruoli?.join(', ') || user?.ruolo}</span>
        <button className="btn-logout" onClick={logout}>Esci</button>
      </div>
    </nav>
  );
}

// frontend/src/components/Sidebar/Sidebar.vue
<script setup>
import { storeToRefs } from 'pinia';
import { useAuthStore } from '../../stores/auth';
import { useModules } from '../../composables/useModules';

const auth = useAuthStore();
const { user } = storeToRefs(auth);
const modules = useModules();
</script>

<template>
  <nav class="sidebar">
    <div class="sidebar-brand">Small CMR</div>
    <ul class="sidebar-nav">

      <template v-if="modules.ore.value">
        <li class="sidebar-section-label">Gestione Ore</li>
        <li><RouterLink to="/ore" active-class="active">Inserimento Ore</RouterLink></li>
        <li v-if="auth.hasRole('admin', 'gestore_commesse')">
          <RouterLink to="/gestione-commesse" active-class="active">Gestione Commesse</RouterLink>
        </li>
      </template>

      <template v-if="modules.richieste.value">
        <li class="sidebar-section-label">Gestione Richieste</li>
        <li><RouterLink to="/" active-class="active" exact-active-class="active">Prenotazioni</RouterLink></li>
        <li v-if="auth.hasRole('admin', 'validatore')">
          <RouterLink to="/approvazioni" active-class="active">Approvazioni</RouterLink>
        </li>
      </template>

      <template v-if="modules.password.value">
        <li class="sidebar-section-label">Vault</li>
        <li><RouterLink to="/vault" active-class="active">Password</RouterLink></li>
      </template>

      <li class="sidebar-section-label">Profilo</li>
      <li><RouterLink to="/profilo" active-class="active">Il mio Profilo</RouterLink></li>

      <template v-if="auth.hasRole('admin')">
        <li class="sidebar-section-label">Anagrafiche</li>
        <li><RouterLink to="/utenti" active-class="active">Utenti</RouterLink></li>
        <li><RouterLink to="/ditte" active-class="active">Ditte</RouterLink></li>
        <li><RouterLink to="/teams" active-class="active">Team</RouterLink></li>
      </template>

    </ul>
    <div class="sidebar-footer">
      <span class="sidebar-user">{{ user?.nome }} {{ user?.cognome }}</span>
      <span class="sidebar-role">{{ user?.ruoli?.join(', ') || user?.ruolo }}</span>
      <button class="btn-logout" @click="auth.logout(); $router.push('/login')">Esci</button>
    </div>
  </nav>
</template>
