// frontend/src/pages/Anagrafiche.vue
<script setup>
import { ref, computed, onMounted, h } from 'vue';
import { storeToRefs } from 'pinia';
import {
  NCard, NTabs, NTabPane, NInput, NSelect, NForm, NFormItem, NButton, NSpace,
  NDataTable, NCheckbox, NTag, NAutoComplete, NAlert, NUpload, NUploadDragger,
  useMessage, useDialog,
} from 'naive-ui';
import api from '../api/client';
import { useAuthStore } from '../stores/auth';

const msg = useMessage();
const dlg = useDialog();
const auth = useAuthStore();
const { user: me } = storeToRefs(auth);

const RUOLI = ['admin', 'validatore', 'gestore_commesse', 'opts'];
const RUOLI_LABELS = { admin: 'Admin', validatore: 'Validatore', gestore_commesse: 'Gestore Commesse', opts: 'Operatore' };
const RUOLO_TYPE = { admin: 'warning', validatore: 'success', gestore_commesse: 'info', opts: 'default' };
const EMPTY = { nome: '', cognome: '', email: '', ditta_id: '', ruoli: ['opts'], password: '' };

const users = ref([]);
const ditte = ref([]);
const tab = ref('ricerca');
const form = ref({ ...EMPTY });
const editingId = ref(null);
const search = ref({ nome: '', cognome: '', email: '', ditta: '', ruolo: null });
const importResult = ref(null);
const importing = ref(false);

const fetchUsers = async () => { users.value = (await api.get('/api/users/')).data; };
const fetchDitte = async () => { ditte.value = (await api.get('/api/ditte')).data; };

onMounted(() => { fetchUsers(); fetchDitte(); });

const getDittaNome = (id) => ditte.value.find(d => String(d.id) === String(id))?.nome ?? '—';

const dittaOptions = computed(() =>
  ditte.value.map(d => ({ label: d.nome, value: String(d.id) }))
);

const ruoloOptions = [
  { label: 'Tutti', value: null },
  ...RUOLI.map(r => ({ label: RUOLI_LABELS[r], value: r })),
];

const filteredUsers = computed(() => users.value.filter(u => {
  const s = search.value;
  if (s.nome    && !u.nome.toLowerCase().includes(s.nome.toLowerCase()))       return false;
  if (s.cognome && !u.cognome.toLowerCase().includes(s.cognome.toLowerCase())) return false;
  if (s.email   && !u.email.toLowerCase().includes(s.email.toLowerCase()))     return false;
  if (s.ditta   && !getDittaNome(u.ditta_id).toLowerCase().includes(s.ditta.toLowerCase())) return false;
  if (s.ruolo   && !u.ruoli?.includes(s.ruolo)) return false;
  return true;
}));

const isSearchActive = computed(() =>
  Object.values(search.value).some(v => v !== '' && v !== null)
);

const resetSearch = () => {
  search.value = { nome: '', cognome: '', email: '', ditta: '', ruolo: null };
};

const resetForm = () => { form.value = { ...EMPTY }; editingId.value = null; };

const submit = async () => {
  try {
    const payload = {
      ...form.value,
      ditta_id: form.value.ditta_id === '' ? null : Number(form.value.ditta_id),
      ruoli: form.value.ruoli,
    };
    if (editingId.value) {
      if (!payload.password) delete payload.password;
      await api.put(`/api/users/${editingId.value}`, payload);
      msg.success('Utente aggiornato');
    } else {
      await api.post('/api/users/', payload);
      msg.success('Utente creato');
    }
    resetForm();
    fetchUsers();
    tab.value = 'ricerca';
  } catch (err) {
    msg.error(err.response?.data?.detail || 'Errore durante il salvataggio.');
  }
};

const edit = (u) => {
  editingId.value = u.id;
  form.value = {
    nome: u.nome, cognome: u.cognome, email: u.email,
    ditta_id: u.ditta_id ? String(u.ditta_id) : '',
    ruoli: u.ruoli || ['opts'],
    password: '',
  };
  tab.value = 'crea';
};

const remove = (u) => {
  dlg.warning({
    title: 'Eliminare l\'utente?',
    content: `"${u.nome} ${u.cognome}" verrà eliminato definitivamente.`,
    positiveText: 'Elimina', negativeText: 'Annulla',
    onPositiveClick: async () => {
      try { await api.delete(`/api/users/${u.id}`); msg.success('Utente eliminato'); fetchUsers(); }
      catch (err) { msg.error(err.response?.data?.detail || 'Errore'); }
    },
  });
};

const toggleRuolo = (r, checked) => {
  let next;
  if (r === 'admin' && checked) next = ['admin'];
  else if (!checked) {
    next = form.value.ruoli.filter(x => x !== r);
    if (!next.length) next = ['opts'];
  } else {
    next = [...form.value.ruoli.filter(x => x !== 'admin'), r];
  }
  form.value.ruoli = next;
};

const downloadTemplate = async () => {
  const r = await api.get('/api/users/import/template', { responseType: 'blob' });
  const url = URL.createObjectURL(r.data);
  const a = document.createElement('a');
  a.href = url; a.download = 'template_utenti.csv'; a.click();
  URL.revokeObjectURL(url);
};

const handleImport = async ({ file }) => {
  importResult.value = null;
  importing.value = true;
  try {
    const formData = new FormData();
    formData.append('file', file.file);
    const r = await api.post('/api/users/import', formData,
      { headers: { 'Content-Type': 'multipart/form-data' } });
    importResult.value = r.data;
    fetchUsers();
  } catch (err) {
    importResult.value = { error: err.response?.data?.detail || 'Errore importazione.' };
  } finally {
    importing.value = false;
  }
};

const columns = computed(() => [
  { title: 'Nome', key: 'nome' },
  { title: 'Cognome', key: 'cognome' },
  { title: 'Email', key: 'email' },
  { title: 'Ditta', key: 'ditta', render: r => getDittaNome(r.ditta_id) },
  {
    title: 'Ruoli', key: 'ruoli',
    render: r => h(NSpace, { size: 'small' }, () =>
      (r.ruoli || []).map(role =>
        h(NTag, { type: RUOLO_TYPE[role] || 'default', size: 'small', round: true },
          () => RUOLI_LABELS[role] || role)
      )
    ),
  },
  {
    title: 'Azioni', key: 'actions', width: 160,
    render: r => h(NSpace, { size: 'small' }, () => {
      const actions = [
        h(NButton, { size: 'small', onClick: () => edit(r) }, () => 'Modifica'),
      ];
      if (r.id !== me.value?.id) {
        actions.push(h(NButton, { size: 'small', type: 'error', ghost: true, onClick: () => remove(r) }, () => 'Elimina'));
      }
      return actions;
    }),
  },
]);
</script>

<template>
  <div class="page">
    <h1>Utenti</h1>
    <NTabs v-model:value="tab" type="line" animated>
      <NTabPane name="ricerca" tab="Ricerca">
        <NCard style="margin-bottom: 1.25rem;">
          <div class="form-row">
            <NFormItem label="Nome" :show-feedback="false">
              <NInput v-model:value="search.nome" placeholder="Mario" clearable />
            </NFormItem>
            <NFormItem label="Cognome" :show-feedback="false">
              <NInput v-model:value="search.cognome" placeholder="Rossi" clearable />
            </NFormItem>
            <NFormItem label="Email" :show-feedback="false">
              <NInput v-model:value="search.email" placeholder="mario@example.com" clearable />
            </NFormItem>
            <NFormItem label="Ditta" :show-feedback="false">
              <NInput v-model:value="search.ditta" placeholder="Acme" clearable />
            </NFormItem>
            <NFormItem label="Ruolo" :show-feedback="false">
              <NSelect v-model:value="search.ruolo" :options="ruoloOptions" clearable />
            </NFormItem>
          </div>
          <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 12px;">
            <NButton v-if="isSearchActive" size="small" @click="resetSearch">Cancella filtri</NButton>
            <span v-else></span>
            <span style="font-size: 0.82rem; color: var(--text-muted);">
              {{ filteredUsers.length }} / {{ users.length }} utenti
            </span>
          </div>
        </NCard>
        <NDataTable :columns="columns" :data="filteredUsers" :bordered="false" />
      </NTabPane>

      <NTabPane name="crea" :tab="editingId ? 'Modifica Utente' : 'Nuovo Utente'">
        <NCard style="margin-bottom: 28px;">
          <NForm @submit.prevent="submit">
            <div class="form-row">
              <NFormItem label="Nome">
                <NInput v-model:value="form.nome" />
              </NFormItem>
              <NFormItem label="Cognome">
                <NInput v-model:value="form.cognome" />
              </NFormItem>
              <NFormItem label="Email">
                <NInput v-model:value="form.email" type="text" placeholder="email@azienda.it" />
              </NFormItem>
              <NFormItem label="Ditta *">
                <NSelect v-model:value="form.ditta_id" :options="dittaOptions" filterable placeholder="Cerca ditta…" />
              </NFormItem>
              <NFormItem label="Ruoli">
                <NSpace vertical size="small">
                  <NCheckbox v-for="r in RUOLI" :key="r"
                             :checked="form.ruoli.includes(r)"
                             :disabled="r !== 'admin' && form.ruoli.includes('admin')"
                             @update:checked="(v) => toggleRuolo(r, v)">
                    <NTag :type="RUOLO_TYPE[r] || 'default'" size="small" round>{{ RUOLI_LABELS[r] }}</NTag>
                  </NCheckbox>
                </NSpace>
              </NFormItem>
              <NFormItem :label="`Password${editingId ? ' (lascia vuoto per non cambiare)' : ''}`">
                <NInput v-model:value="form.password" type="password" show-password-on="click"
                        :placeholder="editingId ? '••••••••' : ''" />
              </NFormItem>
            </div>
            <NSpace>
              <NButton v-if="editingId" @click="resetForm">Annulla modifiche</NButton>
              <NButton type="primary" @click="submit"
                       :disabled="!form.nome || !form.cognome || !form.email || !form.ditta_id || (!editingId && !form.password)">
                {{ editingId ? 'Salva modifiche' : 'Crea Utente' }}
              </NButton>
            </NSpace>
          </NForm>
        </NCard>

        <NCard title="Importa da file">
          <NSpace align="center" style="margin-bottom: 12px;">
            <NButton @click="downloadTemplate">Scarica Template CSV</NButton>
            <NUpload :show-file-list="false" accept=".csv,.xlsx" :custom-request="handleImport" :disabled="importing">
              <NButton type="primary" :loading="importing">
                {{ importing ? 'Importazione...' : 'Importa CSV / XLSX' }}
              </NButton>
            </NUpload>
          </NSpace>
          <NAlert v-if="importResult && !importResult.error"
                  :type="importResult.errori?.length ? 'warning' : 'success'">
            <strong>{{ importResult.creati }} {{ importResult.creati === 1 ? 'utente creato' : 'utenti creati' }}
            <template v-if="importResult.saltati > 0">, {{ importResult.saltati }} saltati</template></strong>
            <ul v-if="importResult.errori?.length" style="margin-top: 8px; padding-left: 18px;">
              <li v-for="(e, i) in importResult.errori" :key="i">{{ e }}</li>
            </ul>
          </NAlert>
          <NAlert v-if="importResult?.error" type="error">{{ importResult.error }}</NAlert>
        </NCard>
      </NTabPane>
    </NTabs>
  </div>
</template>

// frontend/src/pages/Anagrafiche.jsx
import React, { useState, useEffect, useRef } from 'react';
import api from '../api/client';
import { useAuth } from '../context/AuthContext';

const RUOLI = ['admin', 'validatore', 'gestore_commesse', 'opts'];
const RUOLI_LABELS = { admin: 'Admin', validatore: 'Validatore', gestore_commesse: 'Gestore Commesse', opts: 'Operatore' };
const EMPTY_FORM = { nome: '', cognome: '', email: '', ditta_id: '', ruoli: ['opts'], password: '' };

function SearchableDitta({ ditte, value, onChange, required }) {
  const [query, setQuery] = useState('');
  const [open, setOpen] = useState(false);
  const ref = useRef(null);
  const selected = ditte.find(d => String(d.id) === String(value));

  useEffect(() => { setQuery(selected ? selected.nome : ''); }, [value, ditte]);

  useEffect(() => {
    const handler = e => { if (ref.current && !ref.current.contains(e.target)) setOpen(false); };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  const filtered = ditte.filter(d => d.nome.toLowerCase().includes(query.toLowerCase()));

  const select = d => {
    onChange(d ? String(d.id) : '');
    setQuery(d ? d.nome : '');
    setOpen(false);
  };

  return (
    <div ref={ref} style={{ position: 'relative' }}>
      <input
        required={required}
        value={query}
        onChange={e => { setQuery(e.target.value); setOpen(true); onChange(''); }}
        onFocus={() => setOpen(true)}
        placeholder="Cerca ditta…"
      />
      {/* hidden input to satisfy HTML5 required validation */}
      <input type="hidden" required={required} value={value} />
      {open && (
        <div style={{
          position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 100,
          background: 'white', border: '1px solid var(--border)',
          borderRadius: 'var(--radius-sm)', boxShadow: 'var(--shadow-md)',
          maxHeight: '200px', overflowY: 'auto', marginTop: '2px',
        }}>
          {filtered.length === 0
            ? <div style={{ padding: '8px 12px', color: 'var(--text-light)', fontSize: '0.875rem' }}>Nessuna ditta trovata</div>
            : filtered.map(d => (
              <div key={d.id}
                style={{
                  padding: '8px 12px', cursor: 'pointer', fontSize: '0.875rem',
                  background: String(d.id) === String(value) ? 'var(--primary-light)' : 'white',
                  color: String(d.id) === String(value) ? 'var(--primary)' : 'var(--text)',
                }}
                onMouseDown={() => select(d)}>
                {d.nome}
              </div>
            ))
          }
        </div>
      )}
    </div>
  );
}

export default function Anagrafiche() {
  const [activeTab, setActiveTab] = useState('ricerca');
  const [users, setUsers] = useState([]);
  const [ditte, setDitte] = useState([]);
  const [form, setForm] = useState(EMPTY_FORM);
  const [editingId, setEditingId] = useState(null);
  const [error, setError] = useState('');
  const [importResult, setImportResult] = useState(null);
  const [importing, setImporting] = useState(false);
  const [search, setSearch] = useState({ nome: '', cognome: '', email: '', ditta: '', ruolo: '' });
  const fileInputRef = useRef(null);
  const { user: me } = useAuth();

  useEffect(() => {
    fetchUsers();
    api.get('/api/ditte').then(r => setDitte(r.data));
  }, []);

  const fetchUsers = async () => {
    const r = await api.get('/api/users/');
    setUsers(r.data);
  };

  const getDittaNome = id => ditte.find(d => String(d.id) === String(id))?.nome ?? '—';

  const filteredUsers = users.filter(u => {
    if (search.nome    && !u.nome.toLowerCase().includes(search.nome.toLowerCase()))       return false;
    if (search.cognome && !u.cognome.toLowerCase().includes(search.cognome.toLowerCase())) return false;
    if (search.email   && !u.email.toLowerCase().includes(search.email.toLowerCase()))     return false;
    if (search.ditta   && !getDittaNome(u.ditta_id).toLowerCase().includes(search.ditta.toLowerCase())) return false;
    if (search.ruolo   && !u.ruoli?.includes(search.ruolo))                               return false;
    return true;
  });

  const isSearchActive = Object.values(search).some(v => v !== '');

  const handleSubmit = async e => {
    e.preventDefault();
    setError('');
    try {
      const payload = {
        ...form,
        ditta_id: form.ditta_id === '' ? null : Number(form.ditta_id),
        ruoli: form.ruoli,
      };
      if (editingId) {
        if (!payload.password) delete payload.password;
        await api.put(`/api/users/${editingId}`, payload);
      } else {
        await api.post('/api/users/', payload);
      }
      setForm(EMPTY_FORM);
      setEditingId(null);
      fetchUsers();
      setActiveTab('ricerca');
    } catch (err) {
      setError(err.response?.data?.detail || 'Errore durante il salvataggio.');
    }
  };

  const handleEdit = u => {
    setEditingId(u.id);
    setForm({ nome: u.nome, cognome: u.cognome, email: u.email, ditta_id: u.ditta_id ? String(u.ditta_id) : '', ruoli: u.ruoli || ['opts'], password: '' });
    setError('');
    setActiveTab('crea');
  };

  const handleDelete = async id => {
    if (!window.confirm('Eliminare questo utente?')) return;
    try {
      await api.delete(`/api/users/${id}`);
      fetchUsers();
    } catch (err) {
      alert(err.response?.data?.detail || 'Errore durante l\'eliminazione.');
    }
  };

  const handleCancel = () => { setEditingId(null); setForm(EMPTY_FORM); setError(''); };

  const handleDownloadTemplate = async () => {
    const r = await api.get('/api/users/import/template', { responseType: 'blob' });
    const url = URL.createObjectURL(r.data);
    const a = document.createElement('a');
    a.href = url; a.download = 'template_utenti.csv'; a.click();
    URL.revokeObjectURL(url);
  };

  const handleImport = async e => {
    const file = e.target.files?.[0];
    if (!file) return;
    setImportResult(null); setImporting(true);
    try {
      const formData = new FormData();
      formData.append('file', file);
      const r = await api.post('/api/users/import', formData, { headers: { 'Content-Type': 'multipart/form-data' } });
      setImportResult(r.data);
      fetchUsers();
    } catch (err) {
      setImportResult({ error: err.response?.data?.detail || 'Errore durante l\'importazione.' });
    } finally {
      setImporting(false);
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  return (
    <div className="page">
      <h1>Utenti</h1>

      <div className="tabs">
        <button className={`tab-btn${activeTab === 'ricerca' ? ' active' : ''}`} onClick={() => setActiveTab('ricerca')}>Ricerca</button>
        <button className={`tab-btn${activeTab === 'crea' ? ' active' : ''}`}
          onClick={() => { setActiveTab('crea'); if (!editingId) { setForm(EMPTY_FORM); setError(''); } }}>
          {editingId ? 'Modifica Utente' : 'Nuovo Utente'}
        </button>
      </div>

      {activeTab === 'ricerca' && (
        <>
          <div className="card" style={{ marginBottom: 20 }}>
            <div className="form-row">
              <div className="form-group">
                <label>Nome</label>
                <input value={search.nome} onChange={e => setSearch(p => ({ ...p, nome: e.target.value }))} placeholder="Mario" />
              </div>
              <div className="form-group">
                <label>Cognome</label>
                <input value={search.cognome} onChange={e => setSearch(p => ({ ...p, cognome: e.target.value }))} placeholder="Rossi" />
              </div>
              <div className="form-group">
                <label>Email</label>
                <input value={search.email} onChange={e => setSearch(p => ({ ...p, email: e.target.value }))} placeholder="mario@example.com" />
              </div>
              <div className="form-group">
                <label>Ditta</label>
                <input value={search.ditta} onChange={e => setSearch(p => ({ ...p, ditta: e.target.value }))} placeholder="Acme Srl" />
              </div>
              <div className="form-group">
                <label>Ruolo</label>
                <select value={search.ruolo} onChange={e => setSearch(p => ({ ...p, ruolo: e.target.value }))}>
                  <option value="">Tutti</option>
                  {RUOLI.map(r => <option key={r} value={r}>{RUOLI_LABELS[r]}</option>)}
                </select>
              </div>
            </div>
            <div className="form-actions" style={{ marginTop: 8 }}>
              {isSearchActive && (
                <button type="button" className="btn-secondary"
                  onClick={() => setSearch({ nome: '', cognome: '', email: '', ditta: '', ruolo: '' })}>
                  Cancella filtri
                </button>
              )}
              <span style={{ marginLeft: 'auto', fontSize: '0.82rem', color: 'var(--text-muted)', alignSelf: 'center' }}>
                {filteredUsers.length} / {users.length} utenti
              </span>
            </div>
          </div>

          <table className="data-table">
            <thead>
              <tr><th>Nome</th><th>Cognome</th><th>Email</th><th>Ditta</th><th>Ruolo</th><th>Azioni</th></tr>
            </thead>
            <tbody>
              {filteredUsers.length === 0 && (
                <tr><td colSpan={6} style={{ textAlign: 'center', color: 'var(--text-light)', padding: '24px' }}>Nessun utente trovato.</td></tr>
              )}
              {filteredUsers.map(u => (
                <tr key={u.id}>
                  <td>{u.nome}</td>
                  <td>{u.cognome}</td>
                  <td>{u.email}</td>
                  <td>{getDittaNome(u.ditta_id)}</td>
                  <td>
                    {(u.ruoli || []).map(r => (
                      <span key={r} className={`ruolo-badge ${r}`} style={{ marginRight: '0.25rem' }}>
                        {RUOLI_LABELS[r] || r}
                      </span>
                    ))}
                  </td>
                  <td className="table-actions">
                    <button className="btn-sm" onClick={() => handleEdit(u)}>Modifica</button>
                    {u.id !== me?.id && <button className="btn-sm danger" onClick={() => handleDelete(u.id)}>Elimina</button>}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </>
      )}

      {activeTab === 'crea' && (
        <>
          <div className="card" style={{ marginBottom: 28 }}>
            <h2 style={{ marginBottom: 20 }}>{editingId ? 'Modifica Utente' : 'Nuovo Utente'}</h2>
            <form onSubmit={handleSubmit}>
              <div className="form-row">
                <div className="form-group">
                  <label>Nome</label>
                  <input value={form.nome} onChange={e => setForm(p => ({ ...p, nome: e.target.value }))} required />
                </div>
                <div className="form-group">
                  <label>Cognome</label>
                  <input value={form.cognome} onChange={e => setForm(p => ({ ...p, cognome: e.target.value }))} required />
                </div>
                <div className="form-group">
                  <label>Email</label>
                  <input type="email" value={form.email} onChange={e => setForm(p => ({ ...p, email: e.target.value }))} required />
                </div>
                <div className="form-group">
                  <label>Ditta *</label>
                  <SearchableDitta
                    ditte={ditte}
                    value={form.ditta_id}
                    onChange={v => setForm(p => ({ ...p, ditta_id: v }))}
                    required
                  />
                </div>
                <div className="form-group">
                  <label>Ruoli</label>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem', marginTop: '0.3rem' }}>
                    {RUOLI.map(r => {
                      const adminSelected = form.ruoli.includes('admin');
                      const disabled = r !== 'admin' && adminSelected;
                      return (
                        <label key={r} style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', cursor: disabled ? 'not-allowed' : 'pointer', opacity: disabled ? 0.45 : 1 }}>
                          <input type="checkbox"
                            checked={form.ruoli.includes(r)}
                            disabled={disabled}
                            onChange={e => setForm(p => {
                              let next;
                              if (r === 'admin' && e.target.checked) {
                                next = ['admin'];
                              } else if (!e.target.checked) {
                                next = p.ruoli.filter(x => x !== r);
                                if (!next.length) next = ['opts'];
                              } else {
                                next = [...p.ruoli.filter(x => x !== 'admin'), r];
                              }
                              return { ...p, ruoli: next };
                            })}
                          />
                          <span className={`ruolo-badge ${r}`}>{RUOLI_LABELS[r]}</span>
                        </label>
                      );
                    })}
                  </div>
                </div>
                <div className="form-group">
                  <label>Password{editingId ? ' (lascia vuoto per non cambiare)' : ''}</label>
                  <input type="password" value={form.password}
                    onChange={e => setForm(p => ({ ...p, password: e.target.value }))}
                    required={!editingId} placeholder={editingId ? '••••••••' : ''} />
                </div>
              </div>
              {error && <p className="error">{error}</p>}
              <div className="form-actions">
                {editingId && <button type="button" className="btn-secondary" onClick={handleCancel}>Annulla modifiche</button>}
                <button type="submit" className="btn-primary">{editingId ? 'Salva modifiche' : 'Crea Utente'}</button>
              </div>
            </form>
          </div>

          <div className="import-section">
            <h2>Importa da file</h2>
            <button className="btn-secondary" onClick={handleDownloadTemplate}>Scarica Template CSV</button>
            <button className="btn-primary" onClick={() => fileInputRef.current?.click()} disabled={importing}>
              {importing ? 'Importazione...' : 'Importa CSV / XLSX'}
            </button>
            <input ref={fileInputRef} type="file" accept=".csv,.xlsx" style={{ display: 'none' }} onChange={handleImport} />
            {importResult && !importResult.error && (
              <div className={`import-result ${importResult.errori?.length ? 'has-errors' : 'success'}`}>
                <strong>{importResult.creati} {importResult.creati === 1 ? 'utente creato' : 'utenti creati'}{importResult.saltati > 0 && `, ${importResult.saltati} saltati`}</strong>
                {importResult.errori?.length > 0 && <ul className="import-errors">{importResult.errori.map((e, i) => <li key={i}>{e}</li>)}</ul>}
              </div>
            )}
            {importResult?.error && <div className="import-result has-errors"><strong>{importResult.error}</strong></div>}
          </div>
        </>
      )}
    </div>
  );
}
