// frontend/src/pages/Login.jsx
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async e => {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      await login(email, password);
      navigate('/');
    } catch {
      setError('Email o password non corretti.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="login-page">
      <form className="login-card" onSubmit={handleSubmit}>
        <h1>Small CMR</h1>
        <p className="login-subtitle">Accedi al gestionale</p>

        <div className="form-group">
          <label>Email</label>
          <input
            type="email"
            value={email}
            onChange={e => setEmail(e.target.value)}
            required
            autoFocus
            placeholder="nome@azienda.it"
          />
        </div>

        <div className="form-group">
          <label>Password</label>
          <input
            type="password"
            value={password}
            onChange={e => setPassword(e.target.value)}
            required
            placeholder="••••••••"
          />
        </div>

        {error && <p className="error">{error}</p>}

        <button type="submit" className="btn-primary" disabled={loading}>
          {loading ? 'Accesso in corso...' : 'Accedi'}
        </button>
      </form>
    </div>
  );
}

// frontend/src/pages/Login.vue
<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { NCard, NForm, NFormItem, NInput, NButton, NAlert } from 'naive-ui';
import { useAuthStore } from '../stores/auth';

const router = useRouter();
const auth = useAuthStore();

const email = ref('');
const password = ref('');
const error = ref('');
const loading = ref(false);

const submit = async () => {
  error.value = '';
  loading.value = true;
  try {
    await auth.login(email.value, password.value);
    router.push('/');
  } catch {
    error.value = 'Email o password non corretti.';
  } finally {
    loading.value = false;
  }
};
</script>

<template>
  <div class="login-page">
    <NCard class="login-card" :bordered="false">
      <h1>Small CMR</h1>
      <p class="login-subtitle">Accedi al gestionale</p>

      <NForm @submit.prevent="submit">
        <NFormItem label="Email">
          <NInput
            v-model:value="email"
            type="text"
            placeholder="nome@azienda.it"
            autofocus
            @keyup.enter="submit"
          />
        </NFormItem>

        <NFormItem label="Password">
          <NInput
            v-model:value="password"
            type="password"
            placeholder="••••••••"
            show-password-on="click"
            @keyup.enter="submit"
          />
        </NFormItem>

        <NAlert v-if="error" type="error" :show-icon="false" style="margin-bottom: 12px;">
          {{ error }}
        </NAlert>

        <NButton type="primary" block :loading="loading" :disabled="!email || !password" @click="submit">
          {{ loading ? 'Accesso in corso...' : 'Accedi' }}
        </NButton>
      </NForm>
    </NCard>
  </div>
</template>
