// frontend/src/pages/Teams.vue
<script setup>
import { ref, computed, onMounted, h } from 'vue';
import {
  NCard, NTabs, NTabPane, NInput, NForm, NFormItem, NButton, NSpace,
  NDataTable, NCheckbox, NTag, NScrollbar, useMessage, useDialog,
} from 'naive-ui';
import api from '../api/client';

const msg = useMessage();
const dlg = useDialog();

const EMPTY = { name: '', description: '', is_active: true, member_ids: [] };

const teams = ref([]);
const users = ref([]);
const tab = ref('ricerca');
const form = ref({ ...EMPTY });
const editingId = ref(null);
const filtro = ref('');
const memberFilter = ref('');

const fetchTeams = async () => { teams.value = (await api.get('/api/teams')).data; };
const fetchUsers = async () => { users.value = (await api.get('/api/users/')).data; };

onMounted(() => { fetchTeams(); fetchUsers(); });

const teamsFiltrati = computed(() => {
  const q = filtro.value.toLowerCase();
  return teams.value.filter(t =>
    t.name.toLowerCase().includes(q) ||
    (t.description || '').toLowerCase().includes(q)
  );
});

const usersFiltrati = computed(() => {
  const q = memberFilter.value.toLowerCase().trim();
  if (!q) return users.value;
  return users.value.filter(u => `${u.nome} ${u.cognome} ${u.email}`.toLowerCase().includes(q));
});

const resetForm = () => { form.value = { ...EMPTY }; editingId.value = null; };

const submit = async () => {
  try {
    const payload = {
      name: form.value.name,
      description: form.value.description || null,
      is_active: form.value.is_active,
      member_ids: form.value.member_ids,
    };
    if (editingId.value) {
      await api.put(`/api/teams/${editingId.value}`, payload);
      msg.success('Team aggiornato');
    } else {
      await api.post('/api/teams', payload);
      msg.success('Team creato');
    }
    resetForm();
    fetchTeams();
    tab.value = 'ricerca';
  } catch (err) {
    msg.error(err.response?.data?.detail || 'Errore durante il salvataggio.');
  }
};

const edit = (t) => {
  editingId.value = t.id;
  form.value = {
    name: t.name ?? '',
    description: t.description ?? '',
    is_active: t.is_active ?? true,
    member_ids: (t.members || []).map(m => m.id),
  };
  tab.value = 'crea';
};

const remove = (t) => {
  dlg.warning({
    title: 'Eliminare il team?',
    content: `"${t.name}" verrà eliminato.`,
    positiveText: 'Elimina', negativeText: 'Annulla',
    onPositiveClick: async () => {
      try { await api.delete(`/api/teams/${t.id}`); msg.success('Team eliminato'); fetchTeams(); }
      catch (err) { msg.error(err.response?.data?.detail || 'Errore'); }
    },
  });
};

const toggleMember = (uid) => {
  const idx = form.value.member_ids.indexOf(uid);
  if (idx >= 0) form.value.member_ids.splice(idx, 1);
  else form.value.member_ids.push(uid);
};

const columns = computed(() => [
  { title: 'Nome', key: 'name', render: r => h('strong', null, r.name) },
  { title: 'Descrizione', key: 'description', render: r => r.description || '—' },
  { title: 'Membri', key: 'members', render: r => (r.members || []).length },
  {
    title: 'Stato', key: 'is_active',
    render: r => h(NTag, { type: r.is_active ? 'success' : 'default', size: 'small' },
                  () => r.is_active ? 'Attivo' : 'Inattivo'),
  },
  {
    title: 'Azioni', key: 'actions', width: 160,
    render: r => h(NSpace, { size: 'small' }, () => [
      h(NButton, { size: 'small', onClick: () => edit(r) }, () => 'Modifica'),
      h(NButton, { size: 'small', type: 'error', ghost: true, onClick: () => remove(r) }, () => 'Elimina'),
    ]),
  },
]);
</script>

<template>
  <div class="page">
    <h1>Team</h1>
    <NTabs v-model:value="tab" type="line" animated>
      <NTabPane name="ricerca" tab="Ricerca">
        <NCard style="margin-bottom: 1.25rem;">
          <NFormItem label="Cerca team" :show-feedback="false">
            <NInput v-model:value="filtro" placeholder="Filtra per nome o descrizione…" clearable />
          </NFormItem>
        </NCard>
        <NDataTable :columns="columns" :data="teamsFiltrati" :bordered="false" />
      </NTabPane>

      <NTabPane name="crea" :tab="editingId ? 'Modifica Team' : 'Nuovo Team'">
        <NCard style="max-width: 720px;">
          <NForm @submit.prevent="submit">
            <div class="form-row">
              <NFormItem label="Nome *">
                <NInput v-model:value="form.name" placeholder="Es. DevOps" />
              </NFormItem>
              <NFormItem label="Attivo">
                <NCheckbox v-model:checked="form.is_active">Team attivo</NCheckbox>
              </NFormItem>
            </div>
            <NFormItem label="Descrizione">
              <NInput v-model:value="form.description" type="textarea"
                      :autosize="{ minRows: 2, maxRows: 5 }" placeholder="Descrizione del team" />
            </NFormItem>
            <NFormItem :label="`Membri (${form.member_ids.length} selezionati)`">
              <div style="width: 100%;">
                <NInput v-model:value="memberFilter" placeholder="Cerca utente…" clearable style="margin-bottom: 8px;" />
                <NScrollbar style="max-height: 260px; border: 1px solid var(--border); border-radius: 4px;">
                  <div v-if="usersFiltrati.length === 0" style="padding: 12px; color: var(--text-light); text-align: center;">
                    Nessun utente
                  </div>
                  <label v-for="u in usersFiltrati" :key="u.id"
                         style="display: flex; align-items: center; gap: 8px; padding: 6px 12px; border-bottom: 1px solid var(--border-light); cursor: pointer;">
                    <NCheckbox :checked="form.member_ids.includes(u.id)" @update:checked="toggleMember(u.id)" />
                    <div>
                      <div>{{ u.nome }} {{ u.cognome }}</div>
                      <div style="font-size: 0.8em; color: var(--text-light);">{{ u.email }}</div>
                    </div>
                  </label>
                </NScrollbar>
              </div>
            </NFormItem>
            <NSpace>
              <NButton v-if="editingId" @click="resetForm">Annulla</NButton>
              <NButton type="primary" @click="submit" :disabled="!form.name">
                {{ editingId ? 'Salva modifiche' : 'Crea Team' }}
              </NButton>
            </NSpace>
          </NForm>
        </NCard>
      </NTabPane>
    </NTabs>
  </div>
</template>

// frontend/src/pages/Teams.jsx
import React, { useEffect, useState } from 'react';
import api from '../api/client';

const EMPTY_FORM = { name: '', description: '', is_active: true, member_ids: [] };

export default function Teams() {
  const [teams, setTeams] = useState([]);
  const [users, setUsers] = useState([]);
  const [tab, setTab] = useState('ricerca');
  const [form, setForm] = useState(EMPTY_FORM);
  const [editingId, setEditingId] = useState(null);
  const [filtro, setFiltro] = useState('');
  const [error, setError] = useState('');
  const [memberFilter, setMemberFilter] = useState('');

  useEffect(() => { fetchTeams(); fetchUsers(); }, []);

  const fetchTeams = async () => {
    const r = await api.get('/api/teams');
    setTeams(r.data);
  };

  const fetchUsers = async () => {
    const r = await api.get('/api/users');
    setUsers(r.data);
  };

  const handleSubmit = async e => {
    e.preventDefault();
    setError('');
    try {
      const payload = {
        name: form.name,
        description: form.description || null,
        is_active: form.is_active,
        member_ids: form.member_ids,
      };
      if (editingId) {
        await api.put(`/api/teams/${editingId}`, payload);
      } else {
        await api.post('/api/teams', payload);
      }
      setForm(EMPTY_FORM);
      setEditingId(null);
      fetchTeams();
      setTab('ricerca');
    } catch (err) {
      setError(err.response?.data?.detail || 'Errore durante il salvataggio.');
    }
  };

  const handleEdit = t => {
    setEditingId(t.id);
    setForm({
      name: t.name ?? '',
      description: t.description ?? '',
      is_active: t.is_active ?? true,
      member_ids: (t.members || []).map(m => m.id),
    });
    setError('');
    setTab('crea');
  };

  const handleDelete = async id => {
    if (!confirm('Eliminare questo team?')) return;
    try {
      await api.delete(`/api/teams/${id}`);
      fetchTeams();
    } catch (err) {
      alert(err.response?.data?.detail || 'Errore durante l\'eliminazione.');
    }
  };

  const toggleMember = (uid) => {
    setForm(f => ({
      ...f,
      member_ids: f.member_ids.includes(uid)
        ? f.member_ids.filter(id => id !== uid)
        : [...f.member_ids, uid],
    }));
  };

  const teamsFiltrati = teams.filter(t =>
    t.name.toLowerCase().includes(filtro.toLowerCase()) ||
    (t.description || '').toLowerCase().includes(filtro.toLowerCase())
  );

  const usersFiltrati = users.filter(u => {
    const q = memberFilter.toLowerCase().trim();
    if (!q) return true;
    return `${u.nome} ${u.cognome} ${u.email}`.toLowerCase().includes(q);
  });

  return (
    <div className="page">
      <h1>Team</h1>

      <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1.5rem', borderBottom: '2px solid var(--border)' }}>
        {[['ricerca', 'Ricerca'], ['crea', editingId ? 'Modifica Team' : 'Nuovo Team']].map(([key, label]) => (
          <button key={key} onClick={() => { setTab(key); if (key === 'crea' && !editingId) { setForm(EMPTY_FORM); setError(''); } }}
            style={{
              padding: '0.5rem 1.4rem', border: 'none', background: 'none', cursor: 'pointer',
              fontWeight: tab === key ? 700 : 400, fontSize: '0.95rem', marginBottom: '-2px',
              borderBottom: tab === key ? '2px solid var(--accent)' : '2px solid transparent',
              color: tab === key ? 'var(--accent)' : 'var(--text-muted)',
            }}>{label}</button>
        ))}
      </div>

      {tab === 'ricerca' && (
        <>
          <div className="card" style={{ marginBottom: '1.25rem', padding: '1rem 1.25rem' }}>
            <div className="form-group" style={{ marginBottom: 0 }}>
              <label>Cerca team</label>
              <input type="search" placeholder="Filtra per nome o descrizione…"
                value={filtro} onChange={e => setFiltro(e.target.value)} />
            </div>
          </div>

          <table className="data-table">
            <thead>
              <tr>
                <th>Nome</th>
                <th>Descrizione</th>
                <th>Membri</th>
                <th>Stato</th>
                <th>Azioni</th>
              </tr>
            </thead>
            <tbody>
              {teamsFiltrati.length === 0 && (
                <tr><td colSpan={5} style={{ textAlign: 'center', color: 'var(--text-light)', padding: 24 }}>
                  {filtro ? 'Nessun team corrisponde.' : 'Nessun team presente.'}
                </td></tr>
              )}
              {teamsFiltrati.map(t => (
                <tr key={t.id}>
                  <td><strong>{t.name}</strong></td>
                  <td>{t.description || '—'}</td>
                  <td>{(t.members || []).length}</td>
                  <td>{t.is_active ? 'Attivo' : 'Inattivo'}</td>
                  <td className="table-actions">
                    <button className="btn-sm" onClick={() => handleEdit(t)}>Modifica</button>
                    <button className="btn-sm danger" onClick={() => handleDelete(t.id)}>Elimina</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </>
      )}

      {tab === 'crea' && (
        <div className="card" style={{ maxWidth: 720 }}>
          <h2 style={{ marginBottom: '1.25rem' }}>{editingId ? 'Modifica Team' : 'Nuovo Team'}</h2>
          <form onSubmit={handleSubmit}>
            <div className="form-row">
              <div className="form-group">
                <label>Nome *</label>
                <input required placeholder="Es. DevOps"
                  value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} />
              </div>
              <div className="form-group">
                <label>
                  <input type="checkbox" checked={form.is_active}
                    onChange={e => setForm({ ...form, is_active: e.target.checked })} />
                  {' '}Attivo
                </label>
              </div>
            </div>
            <div className="form-group">
              <label>Descrizione</label>
              <textarea rows={3} value={form.description}
                onChange={e => setForm({ ...form, description: e.target.value })}
                placeholder="Descrizione del team" />
            </div>

            <div className="form-group">
              <label>Membri ({form.member_ids.length} selezionati)</label>
              <input type="search" placeholder="Cerca utente…"
                value={memberFilter} onChange={e => setMemberFilter(e.target.value)}
                style={{ marginBottom: 8 }} />
              <div style={{ maxHeight: 260, overflowY: 'auto', border: '1px solid var(--border)', borderRadius: 4 }}>
                {usersFiltrati.length === 0 ? (
                  <div style={{ padding: 12, color: 'var(--text-light)', textAlign: 'center' }}>Nessun utente</div>
                ) : usersFiltrati.map(u => (
                  <label key={u.id} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 12px', borderBottom: '1px solid var(--border-light, #f0f0f0)', cursor: 'pointer' }}>
                    <input type="checkbox"
                      checked={form.member_ids.includes(u.id)}
                      onChange={() => toggleMember(u.id)} />
                    <div>
                      <div>{u.nome} {u.cognome}</div>
                      <div style={{ fontSize: '0.8em', color: 'var(--text-light)' }}>{u.email}</div>
                    </div>
                  </label>
                ))}
              </div>
            </div>

            {error && <p className="error">{error}</p>}
            <div className="form-actions">
              {editingId && (
                <button type="button" className="btn-secondary"
                  onClick={() => { setEditingId(null); setForm(EMPTY_FORM); setError(''); }}>
                  Annulla
                </button>
              )}
              <button type="submit" className="btn-primary">
                {editingId ? 'Salva modifiche' : 'Crea Team'}
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
}
